source/includes/extracts-command-line.yaml, source/index.txt, source/java-api.txt, source/scala-api.txt
DOCS-11636
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-spark-connector/17)
=> Update version to 2.2.2

source/index.txt, source/java-api.txt, source/scala-api.txt
Spark dependency should be 2.2.0
DOCS-11644
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-spark-connector/18)
=> Fix versions

source/includes/extracts-command-line.yaml, source/index.txt, source/java-api.txt, source/scala-api.txt
=> Update to latest Spark Connector versions

source/includes/extracts-command-line.yaml, source/index.txt, source/java-api.txt, source/scala-api.txt
Hey Ross,
Mind taking a look at this PR for the v2.1.2 changes?
Regards,
Jon
=> DOCS-11819 - Update Spark Connector v2.1 version.

source/index.txt
=> Updated index

source/includes/extracts-command-line.yaml, source/index.txt, source/java-api.txt, source/release-notes.txt, source/scala-api.txt
=> Release 2.2.5

source/includes/extracts-command-line.yaml, source/index.txt, source/java-api.txt, source/release-notes.txt, source/scala-api.txt
=> Release 2.1.4

conf.py, source/configuration.txt, source/index.txt, source/python/aggregation.txt, source/python/filters-and-sql.txt, source/python/read-from-mongodb.txt, source/python/write-to-mongodb.txt, source/release-notes.txt, source/scala/datasets-and-sql.txt
JIRA: https://jira.mongodb.org/browse/DOCS-12790
Staging:
- Landing: https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12790/index.html
- Release Notes: https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12790/release-notes.html
- Config: https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12790/configuration.html
Did a find/replace for the `format("mongo")` change.
=> DOCS-12790

source/configuration.txt
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/stevenrenaker/DOCSP-7911/configuration.html
=> DOCSP-7911: Correction needed for shardKey description in Spark Connector docs

conf.py, source/index.txt, source/release-notes.txt
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/stevenrenaker/DOCS-13697/release-notes.html)
=> DOCS-13697: [Spark Connector] release notes for 2.4.2

conf.py
[JIRA](https://jira.mongodb.org/browse/DOCSP-10863)
[Stage](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/john.williams/test1/index.html)
=> (DOCSP-10863): fix permalinks

source/java-api.txt, source/python-api.txt, source/r-api.txt, source/scala-api.txt
[Jira](https://jira.mongodb.org/browse/DOCS-13731)
Stage:
- https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/john.williams/DOCS-13731/scala-api.html#tutorials
- https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/john.williams/DOCS-13731/java-api.html#tutorials
- https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/john.williams/DOCS-13731/python-api.html#tutorials
- https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/john.williams/DOCS-13731/r-api.html#tutorials
=> (DOCS-13731): update links in tutorial sections for next-gen build

conf.py, snooty.toml, source/index.txt, source/release-notes.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-11822)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-11822/index.html)
[Release Notes](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-11822/release-notes.html)
=> [Spark Connector] v3.0.0 release notes

source/configuration.txt, source/index.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6080437109293ae626b91f3d)
=> (DOCSP-15690): Backport DOCSP-15313 to v2.3. (#65)

source/configuration.txt, source/index.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=608044ca09293ae626b98bd9)
=> (DOCSP-15691): Backport DOCSP-15313 to v2.2. (#65)

source/configuration.txt, source/index.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6080477c09293ae626ba3399)
=> (DOCSP-15692): Backport DOCSP-15313 to v2.1. (#65)

conf.py, snooty.toml, source/includes/extracts-command-line.yaml, source/includes/list-prerequisites.rst, source/index.txt, source/java-api.txt, source/scala-api.txt
=> Updated the scala version

source/index.txt
- [JIRA](https://jira.mongodb.org/browse/DOCSP-16458)
- [Stage](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-16458/)
=> DOCSP-16458 Add wording for spark 3.1 support

source/configuration.txt
Added note about hashed shard keys.
https://jira.mongodb.org/browse/DOCSP-18819
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61830328c13055282d673205
https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-18819-ShardedPartitionerClarification/configuration/#mongoshardedpartitioner-configuration
=> DOCSP-18819 mongo sharded partitioner

source/faq.txt, source/scala/datasets-and-sql.txt
* (DOCSP-18818) Improve documentation for unsupported types
https://docs-mongodborg-staging.corp.mongodb.com/NNNNNNN/spark/docsworker-xlarge/NNNNNNNNNNN/
=> (DOCSP-18818) Improve documentation for unsupported types (#77)

source/configuration.txt
https://jira.mongodb.org/browse/DOCS-14027
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61d47a1e41accb3633ad3fed
https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-14027/configuration/#partitioner-configuration
=> (DOCSP-14027) Expand Configuration section

source/includes/pushed-filters.rst, source/python/filters-and-sql.txt
This note may be added to other pages as part of https://jira.mongodb.org/browse/DOCSP-21416
https://jira.mongodb.org/browse/DOCSP-21084
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62437e870ab54725f1430f06
https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/spark-connector/docsworker-xlarge/DOCSP-21084/
=> (DOCSP-21084) Support for pushed filters

source/index.txt
I'll update the dochub link when the blog post goes live. This is the draft: https://docs.google.com/document/d/1qLne4CYIezgFfeNITaxRH-MfVIlIqUjZBHW3xCBc07s/edit
Dochub link not working for me at the moment, investigating that. 
`{"_id":{"$oid":"6245ba2ae4def541c65c2c66"},"url":"https://www.mongodb.com/docs/spark-connector/current/","name":"spark-connector-v10-announcement-blog"}`
https://jira.mongodb.org/browse/DOCSP-21714
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6245bcc92e8f69777c58b39f
https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-21714/
=> (DOCSP-21714) Highlight v10 connector on landing page

source/includes/list-prerequisites.rst, source/index.txt
=> (DOCSP-21416-fix) Fix required versions

source/structured-streaming.txt
=> Structured streaming (removed by mistake)

source/index.txt
=> Hardcode announcement blog link, dochub not working

snooty.toml
* (DOCSP-21748) Add v3 banners
=> (DOCSP-21748) Add banners to v3 and earlier (#101)

snooty.toml, source/index.txt
https://jira.mongodb.org/browse/DOCSP-2187
=> Docsp 21827 2.4.4

.github/pull_request_template.md, REVIEWING.md, config/redirects
=> Add commits from master branch

snooty.toml
=> (DOCSP-21840) Update spark version to 3.0.2

source/structured-streaming.txt
=> Remove scala structured streaming

.github/pull_request_template.md, README.rst
Updates README and PR template
=> community updates

source/structured-streaming.txt
Backport task: https://jira.mongodb.org/browse/DOCSP-22454
=> (DOCSP-21746) Add Scala examples to Structured Streaming page (#122)

source/configuration/read.txt, source/configuration/write.txt, source/includes/sparkconf-partitioner-options-note.rst
Planning to get both copy and technical reviews since some configuration descriptions in the ticket weren't clear.
JIRA - <https://jira.mongodb.org/browse/DOCSP-22626>
Staging -
[Read Config](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-22626-spark-v10-config/configuration/read/)
[Write Config](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-22626-spark-v10-config/configuration/write/)
=> DOCSP-22626: spark v10 connector configs

source/includes/warn-console-stream.rst, source/structured-streaming.txt
JIRA - https://jira.mongodb.org/browse/DOCS-15355
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCS-15355/structured-streaming/
=> (DOCS-15355) Fix example

source/includes/warn-console-stream.rst, source/structured-streaming.txt
* (DOCS-15355) Fix example
JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>
=> (DOCS-15355) Fix example (#129)

source/includes/fact-read-from-change-stream.rst, source/includes/note-trigger-method.rst, source/structured-streaming.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-21747
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-21747/structured-streaming/
=> (DOCSP-21747) Add Java examples

source/includes/fact-read-from-change-stream.rst, source/includes/note-trigger-method.rst, source/structured-streaming.txt
* (DOCSP-21747) Add Java examples
Backport task: https://jira.mongodb.org/browse/DOCSP-23205
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>
=> (DOCSP-21747) Add Java examples (#133)

snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-23995>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-23995-patch-version/>
=> Updating Version to 10.0.3

snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-24799>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-24799/>
=> Update version to 10.0.4

source/configuration/write.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-24641>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-24641-idfieldlist/configuration/write/
=> DOCSP-24641: add example of idFieldList for multiple fields

source/configuration/write.txt
Cherry-pick https://jira.mongodb.org/browse/DOCSP-24641
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/v10.0/configuration/write/
=> DOCSP-24641 cherry-pick to V10.0

snooty.toml
[JIRA](https://jira.mongodb.org/browse/DOCSP-26285)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-26285/)
=> (DOCSP-26285) Bump Patch Version

source/configuration/write.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-26913>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-26913/configuration/write/>
=> DOCSP-26913: Added reference to upsertDocument option

config/redirects, snooty.toml, source/java/api.txt, source/scala/api.txt, source/structured-streaming.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-26312
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/docsp-26312-micro-batch/structured-streaming/
=> [DOCSP-26312] Micro-Batch Processing

source/release-notes.txt
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/release-notes/release-notes/
=> Release notes

source/configuration/read.txt, source/configuration/write.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-26910
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/docsp-26910-bson-types/
=> Docsp 26910 - bson types

snooty.toml, source/release-notes.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-27865>
Staging - 
https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-27865-v10.1.1-patch-release/release-notes/
https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-27865-v10.1.1-patch-release/getting-started/#python-spark-shell
=> DOCSP-27865: v10.1.1 patch release

snooty.toml, source/api-docs.txt, source/index.txt, source/java/api.txt, source/scala/api.txt
Also removed source constants that might confuse the writer more than help them.
JIRA - <https://jira.mongodb.org/browse/DOCSP-27843>
Staging - https://docs-mongodborg-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-27843-API-docs-reformat/
=> DOCSP-27843: API documentation link reformat

source/write-to-mongodb.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-27226
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/docsp-27226-null-fix/write-to-mongodb/
=> DOCSP-27226 - Storing null values

source/getting-started.txt, source/includes/list-prerequisites.rst
JIRA - https://jira.mongodb.org/browse/DOCSP-29281
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/docsp-29281/getting-started/
=> docsp-29281 - add white paper link

source/configuration/write.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-28053
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/docsp-28053-write-concerns/configuration/write/
=> Docsp-28053- write concerns

source/write-to-mongodb.txt
JIRA - https://jira.mongodb.org/browse/DOCS-15611
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/docs-15611-overwrite-warning/write-to-mongodb/
=> DOCS-15611 - add warning

source/configuration/write.txt, source/release-notes.txt, source/write-to-mongodb.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30436>
Staging - 
* Write configuration properties: <https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-30436/configuration/write/#std-label-spark-write-conf>
* Write to MongoDB: <https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-30436/write-to-mongodb/>
* Release notes: <https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-30436/release-notes/>
(Side note: This also alphabetizes the properties on the write configuration page)
=> DOCSP-30436: Added ignoreNullValues

.vscode/settings.json, config/redirects, snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-31279>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/v10.2/>
=> Spark Connector Minor versions 10.2

source/configuration/read.txt, source/configuration/write.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-30967
Staging:
- [Write](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/docsp-30967-comment-option/configuration/write/)
- [Read](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/docsp-30967-comment-option/configuration/read/)
=> docsp-30967 - add comment option

source/configuration/write.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-31168
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/docsp-31168-json-nested/configuration/write/
=> Docsp-31168 - convertJson behavior

source/faq.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-31210
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/docsp-31210-mtls/faq/
=> docsp-31210 - mTLS

source/configuration/read.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-31215
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/docsp-31215-startup-mode/configuration/read/#change-streams
=> DOCSP-31215 - startup mode

snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-30850>
Staging - https://docs-mongodborg-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-30850-EOL-v3.0/
=> DOCSP-30850: EOL v3.0

snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-30850>
Staging - https://docs-mongodborg-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-30850-EOL-v2.3/
=> DOCSP-30850: EOL v2.3

snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-30850>
Staging - https://docs-mongodborg-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-30850-EOL-v2.2/
=> DOCSP-30850 eol v2.2

snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-30850>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-30850-EOL-v2.1/
=> DOCSP-30850 eol v2.1

conf.py
JIRA - https://jira.mongodb.org/browse/DOCSP-30847
Staging - https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/spark-connector/mike.woofter/eol-banner/index.html
[And the current legacy docs for comparison.](https://www.mongodb.com/docs/spark-connector/v1.1/) (Versions 2.1+ were published with Snooty, so they look different than 1.1 and 2.0)
=> docsp-30847 - EOL banner

source/facets.toml, source/java/facets.toml, source/python/facets.toml, source/scala/facets.toml
IRA - <https://jira.mongodb.org/browse/DOCSP-32483>
Hi @mongoKart - here are the facet.toml files for the spark connector repo.  Please merge if everything looks good!
Thanks!
Sarah
=> DOCSP-32483 programmatic tagging script for spark connector repo

source/includes/list-prerequisites.rst, source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-33244>
Staging - 
[Landing page](https://preview-mongodbcchomongodb.gatsbyjs.io/spark-connector/DOCSP-33244-spark-compat/)
[Getting started](https://preview-mongodbcchomongodb.gatsbyjs.io/spark-connector/DOCSP-33244-spark-compat/getting-started/)
=> DOCSP-33244: spark compatibility updates

.github/workflows/backport.yml, source/configuration.txt, source/read-from-mongodb.txt, source/scala/api.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-33955
Staging - https://preview-mongodbmongokart.gatsbyjs.io/spark-connector/docsp-33955-maint/
=> docsp-33955 - alas errors

snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-37439 >
Staging - https://preview-mongodbrustagir.gatsbyjs.io/spark-connector/DOCSP-37439-10.2.2-release/
=> DOCSP-37439: update version to 10.2.2

source/getting-started.txt, source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-38547
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/spark-connector/DOCSP-38547-quickstart-title/getting-started/
=> DOCSP-38547 Update Quick Start Title

snooty.toml, source/batch-mode/batch-read-config.txt
JIRA - 
https://jira.mongodb.org/browse/DOCSP-38841
https://jira.mongodb.org/browse/DOCSP-38919
Staging -
https://preview-mongodbjordansmith721.gatsbyjs.io/spark-connector/version-update-bug-fix/
https://preview-mongodbjordansmith721.gatsbyjs.io/spark-connector/version-update-bug-fix/batch-mode/batch-read-config/#paginateintopartitionspartitioner-configuration
=> Version update and bug fix

config/redirects, snooty.toml, source/includes/list-prerequisites.rst, source/index.txt, source/release-notes.txt
JIRA:
- https://jira.mongodb.org/browse/DOCSP-39193
- https://jira.mongodb.org/browse/DOCSP-39179
Staging - https://preview-mongodbmongokart.gatsbyjs.io/spark-connector/docsp-39193-10.3/
=> v10.3 Updates

source/batch-mode/batch-read-config.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-40130
Staging - https://preview-mongodbmongokart.gatsbyjs.io/spark-connector/docsp-40130-shard-note/batch-mode/batch-read-config/#shardedpartitioner-configuration
=> DOCSP-40130 - Note on Sharded Partitioner

source/release-notes.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41468>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/spark-connector/DOCSP-41468-upgrade-java/release-notes/#mongodb-connector-for-spark-10.4
=> DOCSP-41468: upgrade java driver ver

config/redirects, snooty.toml, source/release-notes.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-42718>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/spark-connector/DOCSP-42718-10.4-release/
=> DOCSP-42718: 10.4 release

source/batch-mode/batch-read-config.txt, source/streaming-mode/streaming-read-config.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-41467
Staging:
- https://preview-mongodbmongokart.gatsbyjs.io/spark-connector/docsp-41467-read-error-handling/batch-mode/batch-read-config/
- https://preview-mongodbmongokart.gatsbyjs.io/spark-connector/docsp-41467-read-error-handling/streaming-mode/streaming-read-config/
=> DOCSP-41467 - Handle bad reads

source/batch-mode.txt, source/batch-mode/batch-read.txt, source/batch-mode/batch-write.txt, source/index.txt, source/streaming-mode.txt, source/streaming-mode/streaming-read.txt, source/streaming-mode/streaming-write.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44953>
Staging - <https://deploy-preview-214--docs-spark-connector.netlify.app/>
=> DOCSP-44953 TOC Relabel

source/batch-mode/batch-read-config.txt
=> Backports DOCSP-45749 to v10.3

source/batch-mode/batch-read-config.txt
=> Backports DOCSP-45749 to v10.2

source/batch-mode/batch-read-config.txt
=> Backports DOCSP-45749 to v10.1

source/batch-mode/batch-read-config.txt
=> Backports DOCSP-45749 to v10.0

snooty.toml
JIRA - https://jira.mongodb.org/browse/DOCSP-47084
https://deploy-preview-236--docs-spark-connector.netlify.app/
=> DOCSP-47084: 10.4.1 release

source/batch-mode/batch-write.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46719>
<li><a href=https://deploy-preview-235--docs-spark-connector.netlify.app/batch-mode/batch-write>batch-mode/batch-write</a></li>
=> DOCSP-46719 Spark Guide 404

.backportrc.json
JIRA - <https://jira.mongodb.org/browse/DOCSP-48172>
No pages to preview
=> DOCSP-48172 add backport json

snooty.toml, source/api-docs.txt, source/batch-mode.txt, source/batch-mode/batch-read-config.txt, source/batch-mode/batch-read.txt, source/batch-mode/batch-write-config.txt, source/batch-mode/batch-write.txt, source/configuration.txt, source/faq.txt, source/getting-started.txt, source/index.txt, source/release-notes.txt, source/streaming-mode.txt, source/streaming-mode/streaming-read-config.txt, source/streaming-mode/streaming-read.txt, source/streaming-mode/streaming-write-config.txt, source/streaming-mode/streaming-write.txt, source/tls.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-47992>
=> DOCSP-47992 - EOL

.github/pull_request_template.md
JIRA - <https://jira.mongodb.org/browse/DOCSP-48941>
No pages to preview
=> DOCSP-48941 - Add PR checklist item

source/configuration.txt, source/faq.txt, source/index.txt, source/java-api.txt, source/java/aggregation.txt, source/java/datasets-and-sql.txt, source/java/read-from-mongodb.txt, source/java/write-to-mongodb.txt, source/python-api.txt, source/python/aggregation.txt, source/python/filters-and-sql.txt, source/python/read-from-mongodb.txt, source/python/write-to-mongodb.txt, source/r-api.txt, source/r/aggregation.txt, source/r/filters-and-sql.txt, source/r/read-from-mongodb.txt, source/r/write-to-mongodb.txt, source/release-notes.txt, source/scala-api.txt, source/scala/aggregation.txt, source/scala/datasets-and-sql.txt, source/scala/read-from-mongodb.txt, source/scala/streaming.txt, source/scala/write-to-mongodb.txt
=> DOCSP-50082: noindex v2.1

source/configuration.txt, source/faq.txt, source/index.txt, source/java-api.txt, source/java/aggregation.txt, source/java/datasets-and-sql.txt, source/java/read-from-mongodb.txt, source/java/write-to-mongodb.txt, source/python-api.txt, source/python/aggregation.txt, source/python/filters-and-sql.txt, source/python/read-from-mongodb.txt, source/python/write-to-mongodb.txt, source/r-api.txt, source/r/aggregation.txt, source/r/filters-and-sql.txt, source/r/read-from-mongodb.txt, source/r/write-to-mongodb.txt, source/release-notes.txt, source/scala-api.txt, source/scala/aggregation.txt, source/scala/datasets-and-sql.txt, source/scala/read-from-mongodb.txt, source/scala/streaming.txt, source/scala/write-to-mongodb.txt
=> DOCSP-50082: noindex v2.2

source/configuration.txt, source/faq.txt, source/index.txt, source/java-api.txt, source/java/aggregation.txt, source/java/datasets-and-sql.txt, source/java/read-from-mongodb.txt, source/java/write-to-mongodb.txt, source/python-api.txt, source/python/aggregation.txt, source/python/filters-and-sql.txt, source/python/read-from-mongodb.txt, source/python/write-to-mongodb.txt, source/r-api.txt, source/r/aggregation.txt, source/r/filters-and-sql.txt, source/r/read-from-mongodb.txt, source/r/write-to-mongodb.txt, source/release-notes.txt, source/scala-api.txt, source/scala/aggregation.txt, source/scala/datasets-and-sql.txt, source/scala/read-from-mongodb.txt, source/scala/streaming.txt, source/scala/write-to-mongodb.txt
=> DOCSP-50082: noindex v2.4

source/configuration.txt, source/faq.txt, source/index.txt, source/java-api.txt, source/java/aggregation.txt, source/java/datasets-and-sql.txt, source/java/read-from-mongodb.txt, source/java/write-to-mongodb.txt, source/python-api.txt, source/python/aggregation.txt, source/python/filters-and-sql.txt, source/python/read-from-mongodb.txt, source/python/write-to-mongodb.txt, source/r-api.txt, source/r/aggregation.txt, source/r/filters-and-sql.txt, source/r/read-from-mongodb.txt, source/r/write-to-mongodb.txt, source/release-notes.txt, source/scala-api.txt, source/scala/aggregation.txt, source/scala/datasets-and-sql.txt, source/scala/read-from-mongodb.txt, source/scala/streaming.txt, source/scala/write-to-mongodb.txt
=> DOCSP-50082: noindex v3.0
