conf.py, source/includes/extracts-command-line.yaml, source/includes/list-prerequisites.rst, source/index.txt, source/java-api.txt, source/release-notes.txt, source/scala-api.txt
**Note:** Ignore the version selector.
Staging: 
- [Index](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12294/index.html)
- [Release Notes](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12294/release-notes.html)
- [Java](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12294/java-api.html)
- [Scala](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12294/scala-api.html)
- [Python](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12294/python-api.html)
- [R](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12294/r-api.html)
=> DOCS-12294 - Release version 2.1.5

conf.py, source/includes/extracts-command-line.yaml, source/includes/list-prerequisites.rst, source/index.txt, source/java-api.txt, source/release-notes.txt, source/scala-api.txt
**Note:** Ignore the version selector.
Staging: 
- [Index](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12293/index.html)
- [Release Notes](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12293/release-notes.html)
- [Java](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12293/java-api.html)
- [Scala](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12293/scala-api.html)
- [Python](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12293/python-api.html)
- [R](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12293/r-api.html)
=> DOCS-12293 - Release version 2.2.6

conf.py, source/includes/extracts-command-line.yaml, source/includes/list-prerequisites.rst, source/index.txt, source/java-api.txt, source/release-notes.txt, source/scala-api.txt
**Note:** Ignore the version selector.
Staging: 
- [Index](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12292/index.html)
- [Release Notes](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12292/release-notes.html)
- [Java](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12292/java-api.html)
- [Scala](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12292/scala-api.html)
- [Python](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12292/python-api.html)
- [R](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12292/r-api.html)
=> DOCS-12292 - Release version 2.3.2

conf.py, source/configuration.txt, source/index.txt, source/python/aggregation.txt, source/python/filters-and-sql.txt, source/python/read-from-mongodb.txt, source/python/write-to-mongodb.txt, source/release-notes.txt, source/scala/datasets-and-sql.txt
JIRA: https://jira.mongodb.org/browse/DOCS-12790
Staging:
- Landing: https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12790v2.3/index.html
- Release Notes: https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12790v2.3/release-notes.html
- Config: https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12790v2.3/configuration.html
Did a find/replace for the format("mongo") change.
**Note:** Ignore the version selector on the top left. That will not show the correct version until the docs are published.
=> DOCS-12790 - 2.3.3 release notes and updates.

conf.py, source/configuration.txt, source/index.txt, source/python/aggregation.txt, source/python/filters-and-sql.txt, source/python/read-from-mongodb.txt, source/python/write-to-mongodb.txt, source/release-notes.txt, source/scala/datasets-and-sql.txt
JIRA: https://jira.mongodb.org/browse/DOCS-12790
Staging:
- Landing: https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12790v2.2/index.html
- Release Notes: https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12790v2.2/release-notes.html
- Config: https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12790v2.2/configuration.html
Did a find/replace for the format("mongo") change.
**Note:** Ignore the version selector on the top left. That will not show the correct version until the docs are published.
=> DOCS-12790 - 2.2.7 release notes and updates.

conf.py, source/configuration.txt, source/index.txt, source/python/aggregation.txt, source/python/filters-and-sql.txt, source/python/read-from-mongodb.txt, source/python/write-to-mongodb.txt, source/release-notes.txt, source/scala/datasets-and-sql.txt
JIRA: https://jira.mongodb.org/browse/DOCS-12790
Staging:
- Landing: https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12790v2.1/index.html
- Release Notes: https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12790v2.1/release-notes.html
- Config: https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/jdestefano/DOCS-12790v2.1/configuration.html
Did a find/replace for the format("mongo") change.
**Note:** Ignore the version selector on the top left. That will not show the correct version until the docs are published.
=> DOCS-12790 - 2.1.6 release notes and updates.

source/configuration.txt
Staged: [Input Configuration](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/stevenrenaker/DOCS-13573/configuration.html#input-configuration)
=> DOCS-13573: [sparkConnector] add samplePoolSize config option

snooty.toml, source/index.txt, source/java-api.txt, source/python-api.txt, source/python/read-from-mongodb.txt, source/r-api.txt, source/scala-api.txt, source/scala/datasets-and-sql.txt, worker.sh
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/snooty-config-v2.3/
Log: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f3c21172f9a5cfb5bfa6b20
```
WARNING(index.txt:53ish): Directive "admonition" has been deprecated
WARNING(configuration.txt:184ish): Monospace text uses two backticks (``)
```
We've deprecated the generic `admonition`, but the named admonitions support titles, so it all works out. Refer to the callouts section of the style guide for guidance.
The `Monospace text uses two backticks…` warning is a false positive that docutils sometimes emits when it gets confused by a `:ref:` -- please ignore it.
=> DOP-1009, DOP-1344: configure v2.3 to build on snooty

snooty.toml, source/index.txt, source/java-api.txt, source/python-api.txt, source/python/read-from-mongodb.txt, source/r-api.txt, source/scala-api.txt, source/scala/datasets-and-sql.txt, worker.sh
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/snooty-config-v2.2/
Log: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f3c21a72f9a5cfb5bfa82e1
```
WARNING(index.txt:53ish): Directive "admonition" has been deprecated
WARNING(configuration.txt:182ish): Monospace text uses two backticks (``)
```
We've deprecated the generic `admonition`, but the named admonitions support titles, so it all works out. Refer to the callouts section of the style guide for guidance.
The `Monospace text uses two backticks…` warning is a false positive that docutils sometimes emits when it gets confused by a `:ref:` -- please ignore it.
=> Snooty config v2.2

snooty.toml, source/faq.txt, source/index.txt, source/java-api.txt, source/python-api.txt, source/python/read-from-mongodb.txt, source/r-api.txt, source/scala-api.txt, source/scala/datasets-and-sql.txt, worker.sh
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/snooty-config-v2.1/
Log: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f3c22142f9a5cfb5bfa93bf
```
WARNING(index.txt:53ish): Directive "admonition" has been deprecated
WARNING(configuration.txt:183ish): Monospace text uses two backticks (``)
```
We've deprecated the generic `admonition`, but the named admonitions support titles, so it all works out. Refer to the callouts section of the style guide for guidance.
The `Monospace text uses two backticks…` warning is a false positive that docutils sometimes emits when it gets confused by a `:ref:` -- please ignore it.
=> DOP-1009, DOP-1344: configure to build on snooty

conf.py, snooty.toml, source/index.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-14335)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/zach.carr/DOCSP-14335/index.html)
Updated compatibility table according to ticket, updated `conf.py` and `snooty.toml` 3.0.0 source constants to 3.0.1.
=> (DOCSP-14335) Update Spark release versions

source/configuration.txt, source/index.txt
@nathan-contino-mongo, I removed "and contain unique values" from the following `shardkey` description. I also fixed a couple of minor issues that cause build warnings.
[STAGE](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-15313/configuration/#mongoshardedpartitioner-configuration)
[JIRA](https://jira.mongodb.org/browse/DOCSP-15313)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=607edaaa09293ae62667070d)
=> (DOCSP-15313): Removed unique values from the shardkey description.

source/configuration.txt, source/includes/sparkconf-partitioner-options-note.rst
Updated the input configuration table to include properties listed in the JIRA ticket. 
I also simplified the prefix note for using `SparkConf`. 
https://jira.mongodb.org/browse/DOCSP-15682
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=618af845c13055282d850c8a
https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-15682-InputConfigs/configuration/#input-configuration
=> DOCSP-15682 input config table

source/faq.txt, source/scala/datasets-and-sql.txt
https://jira.mongodb.org/browse/DOCSP-18818
Added an FAQ item on using MongoDB BSON types that are unsupported in Spark.
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61a663a55314b0809f2ab659
https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-18818/faq/#how-do-i-use-mongodb-bson-types-that-are-unsupported-in-spark-
- I haven't tested the examples - they are pulled from Ross's comments in https://jira.mongodb.org/browse/SPARK-132. Do we need to test all code examples or is a technical review to confirm acceptable? 
- Do we need examples in other languages, or to more clearly label the examples "Scala?"
=> (DOCSP-18818) Improve documentation for unsupported types

source/configuration/read.txt, source/configuration/write.txt, source/faq.txt, source/includes/sparkconf-partitioner-options-note.rst
Documenting the partitioners in this PR: https://github.com/mongodb/mongo-spark/pull/63
This is old Spark content, updated for v10. Several partitioners are removed.
**For tech review**
Please confirm the partitioner option names, I'm not sure if they've changed. `partitionKey` in particular is a list now.
- partitionKey
- partitionSizeMB
- samplesPerPartition
- shardkey
- maxNumberOfPartitions
https://jira.mongodb.org/browse/DOCSP-20565
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=621bd1a09c4c7f6bfbfe1079
https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-20565/configuration/read/
=> (DOCSP-20565) v10 partitioners

source/configuration/read.txt, source/structured-streaming.txt
Moving this PR (https://github.com/mongodb/docs-spark-connector/pull/100) here because I updated the v10.0 branch name.
Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-21735
Snooty build log:
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=624f07c00fdfea9c3737f93f
Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-21735-v10.0/configuration/read/#change-streams
=> (DOCSP-21735) Add fullDocument config option

source/configuration/read.txt, source/configuration/write.txt, source/includes/extracts-command-line.yaml, source/java/api.txt, source/python/api.txt, source/python/read-from-mongodb.txt, source/python/write-to-mongodb.txt, source/scala/api.txt
Updated `uri` -> `connection.uri`
https://jira.mongodb.org/browse/DOCSP-21884
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62505dbd0fdfea9c377b239c
https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-21884/configuration/write/
https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-21884/configuration/read/
=> DOCSP-21884 updated config uri name

source/structured-streaming.txt
https://jira.mongodb.org/browse/DOCSP-21746
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=624f37b20fdfea9c3742a5ea
https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-21746/structured-streaming/
=> (DOCSP-21746) Add Scala examples to Structured Streaming page

source/includes/sparkconf-partitioner-options-note.rst
Note: this PR is on the v10.0 branch as the main branch is currently out of sync with v10.0. See [this ticket](https://jira.mongodb.org/browse/DOCSP-25732) for more info.
JIRA - <https://jira.mongodb.org/browse/DOCS-15666>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCS-15666-fix-read-config-admonition/configuration/read/
=> DOCS-15666: fix read config admonition

source/java/sql.txt
No JIRA ticket
This PR fixes the code-block rST indentation which silently failed to apply syntax highlighting for the specified language. While it's beyond expectations to review each file, to verify the syntax highlighting is applied, you'll need to individually inspect each code block with Chrome Tools for the "java" (or other) style in the code component:
Staging:
[SQL Queries](https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/110922-fix-code-block-indentation/read-from-mongodb/#sql-queries)
=> Fix code block indentation

source/structured-streaming.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-27521
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/v10.0/structured-streaming/
=> DOCSP-27521 - Fix Broken PySpark Links in v10.0

source/java/write-to-mongodb.txt
Note: This PR is merging to v3.0 and being backported to versions before that. This fix isn't applicable in versions after 3.0.
JIRA - https://jira.mongodb.org/browse/DOCSP-29697
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/docsp-29697-variable-name/java/write-to-mongodb/
=> DOCSP-29697 - fix variable name

source/configuration/read.txt, source/structured-streaming.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30376>
Staging - 
* Structured streaming: https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-30376/structured-streaming/#configuring-a-read-stream-from-mongodb
* Partition configurations: https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/DOCSP-30376/configuration/read/#partitioner-configurations
=> DOCSP-30376: Clarified streaming produces a single partition

config/redirects, snooty.toml, source/configuration/read.txt, source/read-from-mongodb.txt, source/structured-streaming.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-31169
Staging:
-  https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/docsp-31169-infer-schema/read-from-mongodb/
- https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/docsp-31169-infer-schema/configuration/read/#change-streams
=> docsp-31169 - change stream schema inference

source/release-notes.txt
Jira - https://jira.mongodb.org/browse/DOCSP-31503
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/spark-connector/docsworker-xlarge/whats-new/release-notes/
=> DOCSP-31503 - 10.2 Spark Features

source/api-docs.txt
Surfaces links contained within the section in case the reader navigates directly to the API page. Another solution could be to eliminate the ToC so that the links only show up in the content of the API documentation page.
JIRA - None
Staging - [API Documentation](https://preview-mongodbcchomongodb.gatsbyjs.io/spark-connector/101023-add-api-docs-links/api-docs/)
=> add links to content of the API documentation page

source/includes/note-trigger-method.rst, source/streaming-mode/streaming-read-config.txt, source/streaming-mode/streaming-write.txt
Removed nested admonitions following [this doc](https://docs.google.com/document/d/1yMbng-EPOQ82bAzBTC2VJwIvsUBOSCJh21cGbDoe1a8/edit#heading=h.8t0xo8i29om4)
JIRA - https://jira.mongodb.org/browse/DOCSP-42969
Staging:
- https://preview-mongodbmongokart.gatsbyjs.io/spark-connector/docsp-42969-nested-components/batch-mode/batch-read-config/
- https://preview-mongodbmongokart.gatsbyjs.io/spark-connector/docsp-42969-nested-components/streaming-mode/streaming-read-config/
- https://preview-mongodbmongokart.gatsbyjs.io/spark-connector/docsp-42969-nested-components/streaming-mode/streaming-write/
=> DOCSP-42969 - Remove nested admonitions

source/batch-mode/batch-read-config.txt, source/batch-mode/batch-read.txt, source/streaming-mode/streaming-read-config.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-41049
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/spark-connector/DOCSP-41049-schemaHints/batch-mode/batch-read/#specify-known-fields-with-schema-hints
=> DOCSP-41049 schemaHint option

source/batch-mode/batch-read-config.txt
No content changes other than denesting nested admonition.
The build is clean, but there's a failing check to "check autobuilder for errors" due to autobuilder not being set up-- this is no longer relevant since we use Netlify for builds.
JIRA - https://jira.mongodb.org/browse/DOCSP-45749
Staging - https://deploy-preview-220--docs-spark-connector.netlify.app/batch-mode/batch-read-config/#overview
=> (DOCSP-45749) Denests last phase 1 nested component for spark connector

source/batch-mode/batch-read-config.txt
Backports #220
Build is clean, autobuilder failed check is due to autobuilder not being set up (no longer relevant)
=> Backports DOCSP-45749 to v10.4

source/batch-mode/batch-read.txt, source/java/filters.rst
JIRA - <https://jira.mongodb.org/browse/DOCSP-33990>
Staging - <https://deploy-preview-226--docs-spark-connector.netlify.app/batch-mode/batch-read/#filters>
=> [Spark] Add Filters section for Java

source/includes/connection-read-config.rst
JIRA - <https://jira.mongodb.org/browse/DOCSP-43812>
No pages to preview
=> [SPARK] Remove unsupported configuration 'spark.mongodb.read.readPreference.name'

.github/workflows/vale-tdbx.yml, source/getting-started.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-31186>
<li><a href=https://deploy-preview-243--docs-spark-connector.netlify.app/getting-started>getting-started</a></li>
=> DOCSP-31186 Add sections for connections

.github/workflows/vale-tdbx.yml, source/getting-started.txt
This will backport the following commits from `master` to `v10.3`:
- [DOCSP-31186 Add sections for connections (#243)](https://github.com/mongodb/docs-spark-connector/pull/243)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
=> [v10.3] DOCSP-31186 Add sections for connections (#243)

source/api-docs.txt, source/batch-mode.txt, source/batch-mode/batch-read-config.txt, source/batch-mode/batch-read.txt, source/batch-mode/batch-write-config.txt, source/batch-mode/batch-write.txt, source/configuration.txt, source/faq.txt, source/getting-started.txt, source/index.txt, source/release-notes.txt, source/streaming-mode.txt, source/streaming-mode/streaming-read-config.txt, source/streaming-mode/streaming-read.txt, source/streaming-mode/streaming-write-config.txt, source/streaming-mode/streaming-write.txt, source/tls.txt
Adds missing meta descriptions generated by the Education AI Team\n\nSOURCE: https://docs.google.com/spreadsheets/d/1fdrjF4Ms9fMl96zLiLGsYD_V38rTfPLuKs5VQk4vz6E/edit?gid=1166644539
=> Add missing meta descriptions

snooty.toml, source/batch-mode/batch-read-config.txt, source/release-notes.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-49645>
<li><a href=https://deploy-preview-252--docs-spark-connector.netlify.app/batch-mode/batch-read-config>batch-mode/batch-read-config</a></li><li><a href=https://deploy-preview-252--docs-spark-connector.netlify.app/release-notes>release-notes</a></li>
=> [SPARK] Set Auto Bucket Partitioner to be the default partitioning strategy

source/configuration.txt, source/faq.txt, source/index.txt, source/java-api.txt, source/java/aggregation.txt, source/java/datasets-and-sql.txt, source/java/read-from-mongodb.txt, source/java/write-to-mongodb.txt, source/python-api.txt, source/python/aggregation.txt, source/python/filters-and-sql.txt, source/python/read-from-mongodb.txt, source/python/write-to-mongodb.txt, source/r-api.txt, source/r/aggregation.txt, source/r/filters-and-sql.txt, source/r/read-from-mongodb.txt, source/r/write-to-mongodb.txt, source/release-notes.txt, source/scala-api.txt, source/scala/aggregation.txt, source/scala/datasets-and-sql.txt, source/scala/read-from-mongodb.txt, source/scala/streaming.txt, source/scala/write-to-mongodb.txt
=> DOCSP-50082: noindex v2.3

source/batch-mode/batch-write-config.txt, source/streaming-mode/streaming-write-config.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48557>
<li><a href=https://deploy-preview-261--docs-spark-connector.netlify.app/batch-mode/batch-write-config>batch-mode/batch-write-config</a></li><li><a href=https://deploy-preview-261--docs-spark-connector.netlify.app/streaming-mode/streaming-write-config>streaming-mode/streaming-write-config</a></li>
=> DOCSP-48557 Update Spark streaming write configuration to include all batch options

source/batch-mode/batch-write-config.txt, source/streaming-mode/streaming-write-config.txt
This will backport the following commits from `master` to `v10.4`:
- [DOCSP-48557 Update Spark streaming write configuration to include all batch options (#261)](https://github.com/mongodb/docs-spark-connector/pull/261)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
=> [v10.4] DOCSP-48557 Update Spark streaming write configuration to include all batch options (#261)

source/batch-mode/batch-write-config.txt, source/streaming-mode/streaming-write-config.txt
This will backport the following commits from `master` to `v10.2`:
- [DOCSP-48557 Update Spark streaming write configuration to include all batch options (#261)](https://github.com/mongodb/docs-spark-connector/pull/261)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
=> [v10.2] DOCSP-48557 Update Spark streaming write configuration to include all batch options (#261)

snooty.toml, source/api-docs.txt, source/batch-mode.txt, source/batch-mode/batch-read-config.txt, source/batch-mode/batch-read.txt, source/batch-mode/batch-write-config.txt, source/batch-mode/batch-write.txt, source/configuration.txt, source/faq.txt, source/getting-started.txt, source/index.txt, source/release-notes.txt, source/streaming-mode.txt, source/streaming-mode/streaming-read-config.txt, source/streaming-mode/streaming-read.txt, source/streaming-mode/streaming-write-config.txt, source/streaming-mode/streaming-write.txt, source/tls.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-50360
https://deploy-preview-267--docs-spark-connector.netlify.app/
=> DOCSP-50360: v10.2 EOL
